cmd: "mvn package"
name: "build"
args:

sh: true,
cwd: "c:/var/www/shape"
env:
  VARIABLE1: "VALUE1"
  VARIABLE2: "VALUE2"
errorMatch:
  - ^regexp1$
  - ^regexp2$
warningMatch:
  - ^regexp1$
  - ^regexp2$
keymap: <keymap string>
atomCommandName: namespace:command
targets:
  extraTargetName:
      cmd: "java -jar target/shape.jar -w false  -b 20"
      #cmd: "mvn package"

      args:
      # (any previous options are viable here except `targets` itself)
